NT-192 Speech To Text
Negotiation-Trainer/negotiation-trainer pull request #10
Opened 2024-03-19 09:48 UTC by PatrickSlag

2024-03-19 11:26 UTC, PatrickSlag commented
If somebody could test this in safari. it should work but just to be sure

2024-03-19 13:45 UTC, jortdr commented
Tested on Safari Mac and on Safari iPad. Works, but not for the second try.

2024-03-19 13:48 UTC, jortdr requested changes

2024-03-19 13:48 UTC, jortdr commented on Assets/Scripts/Presenters/SpeechPresenter.cs
> +            StartSpeechRecognition();
Should check if platform is supported and return if not supported.

2024-03-19 13:48 UTC, jortdr commented on Assets/Plugins/TextToSpeech.jslib
format this file?

2024-03-26 14:52 UTC, VarioCode approved these changes, later dismissed

2024-03-26 14:59 UTC, jortdr approved these changes

2024-03-26 15:01 UTC, VarioCode approved these changes

2024-03-26 15:06 UTC, merged