Feature/NT-166 hourglass UI creation
Negotiation-Trainer/negotiation-trainer pull request #11
Opened 2024-03-19 12:25 UTC by jortdr

Hourglass UI added
Coded falling sand
Cleaned up existing code.

2024-03-19 12:40 UTC, PatrickSlag requested changes
can there be a test scene or gif of how this works/looks?

2024-03-19 12:40 UTC, PatrickSlag commented on Assets/Scripts/Presenters/HourglassPresenter.cs
> +        public Transform sandTop;
i think you should use [SerializeField] private to get unity object instead of just public

2024-03-19 13:15 UTC, jortdr commented
![Untitled-2-ezgif com-optimize](https://github.com/Negotiation-Trainer/negotiation-trainer/assets/39172426/e74fee0c-07cc-4e21-8b49-619d5f08dd1f)

@PatrickSlag here's a gif of how it works

2024-03-21 08:30 UTC, PatrickSlag submitted a review, later dismissed

2024-03-21 09:51 UTC, VarioCode requested changes

2024-03-21 09:51 UTC, VarioCode commented on .vsconfig
> +{
Shouldn't this be in the git ignore?

2024-03-21 09:52 UTC, VarioCode commented on .vsconfig
> +{
Shouldn't this be in the git ignore?

2024-03-21 14:31 UTC, VarioCode approved these changes

2024-03-21 14:59 UTC, PatrickSlag approved these changes

2024-03-21 14:59 UTC, merged