Feature NT-194 Dialogue presenter
Negotiation-Trainer/negotiation-trainer pull request #16
Opened 2024-03-20 12:13 UTC by PatrickSlag

2024-03-21 09:48 UTC, VarioCode approved these changes, later dismissed

2024-03-21 15:09 UTC, jortdr approved these changes

2024-03-21 15:09 UTC, jortdr commented on Assets/Scripts/Presenters/DialoguePresenter.cs
> +        public void QueMessages(IMessage[] messages)
Queue

2024-03-21 15:09 UTC, jortdr commented on Assets/Scripts/Presenters/DialoguePresenter.cs
> +        private Queue<IMessage> _dialogueQue = new Queue<IMessage>();
Queue

2024-03-21 15:09 UTC, jortdr requested changes
Que?

2024-03-21 15:37 UTC, VarioCode submitted a review, later dismissed
No more que nice

2024-03-22 07:01 UTC, VarioCode submitted a review, later dismissed

2024-03-22 07:03 UTC, jortdr submitted a review, later dismissed
Que

2024-03-22 07:14 UTC, VarioCode approved these changes, later dismissed

2024-03-22 07:15 UTC, jortdr approved these changes, later dismissed

2024-03-22 07:25 UTC, jortdr approved these changes

2024-03-22 07:25 UTC, VarioCode approved these changes

2024-03-22 07:33 UTC, merged