NT 140 intro Instruction cutscene
Negotiation-Trainer/negotiation-trainer pull request #22
Opened 2024-03-21 15:02 UTC by PatrickSlag

2024-03-21 15:35 UTC, VarioCode requested changes
I made a few comment either fix the issues or create a TD story for them. If you choose the 2nd option, please comment it under this message so I can go over it and see if I miss anything.

2024-03-21 15:35 UTC, VarioCode commented on Assets/Scripts/GameManager.cs
> +    /*private void OnCutSceneEnd(PlayableDirector director)
Commented out logic can be removed

2024-03-21 15:35 UTC, VarioCode commented on Assets/Scripts/GameManager.cs
>  public class GameManager : MonoBehaviour
The game manager should only be used for managing state...why was so much logic added here?

2024-03-21 15:35 UTC, VarioCode commented on Assets/Scripts/GameManager.cs
> +                //playableDirector.stopped += OnCutSceneEnd;
Commented out logic can be removed

2024-03-21 15:35 UTC, VarioCode commented on Assets/Scripts/Presenters/DialoguePresenter.cs
> +        //[SerializeField] private Button DebugDialogueButton;
Commented out logic can be removed

2024-03-21 15:35 UTC, VarioCode commented on Assets/Scripts/Presenters/DialoguePresenter.cs
> +            //DebugDialogueButton.onClick.AddListener(DebugStartDialogue);
Commented logic please remove

2024-03-21 15:35 UTC, VarioCode commented on Assets/Scripts/Presenters/DialoguePresenter.cs
> +        /*//Debug UI
Can be deleted

2024-03-21 17:30 UTC, PatrickSlag commented on Assets/Scripts/GameManager.cs
>  public class GameManager : MonoBehaviour
https://038games.atlassian.net/browse/NT-217

2024-03-22 06:50 UTC, VarioCode approved these changes

2024-03-22 06:50 UTC, VarioCode commented on Assets/Scripts/GameManager.cs
>  public class GameManager : MonoBehaviour
Alr gtg

2024-03-22 06:57 UTC, jortdr approved these changes

2024-03-22 06:58 UTC, merged