NT-39 Text To Speech
Negotiation-Trainer/negotiation-trainer pull request #30
Opened 2024-03-27 12:23 UTC by PatrickSlag

2024-04-02 09:59 UTC, VarioCode requested changes

2024-04-02 09:59 UTC, VarioCode commented on Assets/Scripts/Presenters/SpeechPresenter.cs
> +                    Debug.LogWarning("Speech synthesis not supported on your platform or browser");
Can we also give feedback to the User inside the UI, not only via a Debug message.

2024-04-02 09:59 UTC, VarioCode commented on Assets/Scripts/Presenters/SpeechPresenter.cs
> +                    Debug.LogWarning("Speech recognition not supported on your platform or browser");
I would like some error message in the UI, to inform the user, no real user is gonna look inside the logging.

2024-04-03 08:12 UTC, PatrickSlag commented
https://038games.atlassian.net/browse/NT-246

2024-04-04 08:03 UTC, VarioCode approved these changes

2024-04-04 08:06 UTC, VarioCode approved these changes, later dismissed

2024-04-04 08:46 UTC, VarioCode submitted a review, later dismissed

2024-04-04 09:32 UTC, jortdr approved these changes
lgtm

2024-04-04 10:25 UTC, VarioCode approved these changes

2024-04-04 13:01 UTC, merged