NT-381 added hourglass events
Negotiation-Trainer/negotiation-trainer pull request #81
Opened 2024-05-22 09:27 UTC by jortdr

2024-05-22 10:02 UTC, PatrickSlag requested changes
It was not written down, but the storm incoming effects require an event to be triggered halfway or three quarters through the time

2024-05-22 10:02 UTC, PatrickSlag commented on Assets/Scripts/Presenters/HourglassPresenter.cs
> +        public Action OnHourglassFinished;
I think it would be more useful if this was a unity event so that you could also add it in the editor

2024-05-22 10:02 UTC, PatrickSlag commented on Assets/Resources/ServiceLibrary.dll
dll updated ?

2024-05-22 11:26 UTC, VarioCode approved these changes, later dismissed
Other then @PatrickSlag's comments, lgtm

2024-05-22 11:26 UTC, VarioCode commented on Assets/Scripts/Presenters/HourglassPresenter.cs
> +        public Action OnHourglassFinished;
Good point

2024-05-23 08:20 UTC, jortdr commented on Assets/Resources/ServiceLibrary.dll
fixed

2024-05-23 08:42 UTC, PatrickSlag requested changes

2024-05-23 08:42 UTC, PatrickSlag commented on Assets/Scripts/Presenters/HourglassPresenter.cs
> +        public event EventHandler OnStormEvent;
```suggestion
        public UnityEvent OnHourglassFinished;
        public UnityEvent OnStormEvent;
```

2024-05-23 08:42 UTC, PatrickSlag commented on Assets/Scripts/Presenters/HourglassPresenter.cs
> +        public event EventHandler OnStormEvent;
It needs to be a UnityEvent to be accessible in the editor

2024-05-23 08:51 UTC, PatrickSlag approved these changes, later dismissed
Oh, i just noticed the variable names don't follow the conventions, but that can be fixed in de code cleanup story

2024-05-23 08:58 UTC, jortdr commented
> Oh, i just noticed the variable names don't follow the conventions, but that can be fixed in de code cleanup story

You mean the Unity Events? I think that convention is stupid, since normal events do follow CamelCase naming, but UnityEvent doesn't, for some reason.

2024-05-23 09:15 UTC, PatrickSlag commented
yhea that, but also the _ in front of private

2024-05-23 09:16 UTC, jortdr commented
> yhea that, but also the _ in front of private

Const or read-only private variables aren't prefixed with _

2024-05-23 09:29 UTC, PatrickSlag approved these changes

2024-05-23 15:20 UTC, merged